# Generated by Django 3.2.7 on 2021-09-26 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Device_ID', models.CharField(max_length=100)),
                ('DATE', models.DateTimeField(auto_now=True)),
                ('Position', models.CharField(choices=[('右腳踝', '右腳踝'), ('左腳踝', '左腳踝'), ('右膝蓋', '右膝蓋'), ('左膝蓋', '左膝蓋'), ('右大腿', '右大腿'), ('左大腿', '左大腿'), ('腰', '腰')], max_length=32, verbose_name='POSITION')),
                ('UUID', models.CharField(max_length=100)),
                ('DATA', models.CharField(max_length=10000)),
            ],
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Device_ID', models.CharField(max_length=100)),
                ('UUID', models.CharField(max_length=100)),
                ('Position', models.CharField(choices=[('右腳踝', '右腳踝'), ('左腳踝', '左腳踝'), ('右膝蓋', '右膝蓋'), ('左膝蓋', '左膝蓋'), ('右大腿', '右大腿'), ('左大腿', '左大腿'), ('腰', '腰')], max_length=32, verbose_name='POSITION')),
                ('Leader_IP', models.CharField(max_length=300)),
            ],
        ),
    ]
